[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.1.5" #dont change
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.03.01"
barcodeScanner = "17.3.0"
objectDetection = "17.0.2"
materialIcons = "1.7.8"
navigation = "2.9.7"
koin = "4.1.1"
coil = "3.4.0"
lottie = "6.7.1"
camerax = "1.6.0"
permissions = "0.37.3"
ksp = "2.3.4"
sqlDelight = "2.3.2"
dataStore = "1.2.1"
kotlinCollections = "0.4.0"
kotlinSerialization = "1.11.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
ml-kit-barcode-scanner = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanner" }
ml-kit-obj-detection = { module = "com.google.mlkit:object-detection", version.ref = "objectDetection" }
ml-kit-obj-detection-custom = { module = "com.google.mlkit:object-detection-custom", version.ref = "objectDetection" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
koin-android = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera2-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
cameraView = { module = "androidx.camera:camera-view", version.ref = "camerax" }
permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "permissions" }
sql-delight = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight"}
sql-delight-dialect = { module = "app.cash.sqldelight:sqlite-3-38-dialect", version.ref = "sqlDelight"}
sql-delight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight"}
sql-delight-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqlDelight"}
dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "dataStore" }
kotlin-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinCollections" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
sql-delight = { id = "app.cash.sqldelight", version.ref = "sqlDelight"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


