package com.lonwulf.labs.easyshopmanager.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Primary = Color(0xFF35BB6D)
val Tertiary = Color(0xFF9BFF98)
val Error = Color(0xFFFF3B53)
val Neutral = Color(0xFFFAFFFF)

val Seed = Color(0xFF35BB6D)

val PrimaryLightHighContrast = Color(0xFF002B13)
val OnPrimaryLightHighContrast = Color(0xFF73F39E)
val PrimaryContainerLightHighContrast = Color(0xFF005F31)
val OnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val InversePrimaryLightHighContrast = Color(0xFF79F9A3)
val SecondaryLightHighContrast = Color(0xFF16281A)
val OnSecondaryLightHighContrast = Color(0xFFCAE0CB)
val SecondaryContainerLightHighContrast = Color(0xFF435747)
val OnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val TertiaryLightHighContrast = Color(0xFF002B06)
val OnTertiaryLightHighContrast = Color(0xFF8DF08B)
val TertiaryContainerLightHighContrast = Color(0xFF006019)
val OnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val BackgroundLightHighContrast = Color(0xFFF5FAFA)
val OnBackgroundLightHighContrast = Color(0xFF000000)
val SurfaceLightHighContrast = Color(0xFFF5FAFA)
val OnSurfaceLightHighContrast = Color(0xFF000000)
val SurfaceVariantLightHighContrast = Color(0xFFD8E5E6)
val OnSurfaceVariantLightHighContrast = Color(0xFF1A2627)
val SurfaceTintLightHighContrast = Color(0xFF002B13)
val InverseSurfaceLightHighContrast = Color(0xFF0A0F10)
val InverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val ErrorLightHighContrast = Color(0xFF50000E)
val OnErrorLightHighContrast = Color(0xFFFFCECE)
val ErrorContainerLightHighContrast = Color(0xFFA80028)
val OnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val OutlineLightHighContrast = Color(0xFF394546)
val OutlineVariantLightHighContrast = Color(0xFF485455)
val ScrimLightHighContrast = Color(0xFF000000)
val SurfaceBrightLightHighContrast = Color(0xFFF5FAFA)
val SurfaceContainerLightHighContrast = Color(0xFFE6F0F0)
val SurfaceContainerHighLightHighContrast = Color(0xFFE0EAEB)
val SurfaceContainerHighestLightHighContrast = Color(0xFFD8E5E6)
val SurfaceContainerLowLightHighContrast = Color(0xFFEDF5F5)
val SurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val SurfaceDimLightHighContrast = Color(0xFFD0DCDD)

val PrimaryDarkHighContrast = Color(0xFF7FFFA9)
val OnPrimaryDarkHighContrast = Color(0xFF003418)
val PrimaryContainerDarkHighContrast = Color(0xFF34BA6C)
val OnPrimaryContainerDarkHighContrast = Color(0xFF000000)
val InversePrimaryDarkHighContrast = Color(0xFF004220)
val SecondaryDarkHighContrast = Color(0xFFD5EBD6)
val OnSecondaryDarkHighContrast = Color(0xFF1E3022)
val SecondaryContainerDarkHighContrast = Color(0xFF94A996)
val OnSecondaryContainerDarkHighContrast = Color(0xFF000000)
val TertiaryDarkHighContrast = Color(0xFFE0FFD9)
val OnTertiaryDarkHighContrast = Color(0xFF00400D)
val TertiaryContainerDarkHighContrast = Color(0xFF9BFF98)
val OnTertiaryContainerDarkHighContrast = Color(0xFF00360A)
val BackgroundDarkHighContrast = Color(0xFF0A0F10)
val OnBackgroundDarkHighContrast = Color(0xFFFFFFFF)
val SurfaceDarkHighContrast = Color(0xFF0A0F10)
val OnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val SurfaceVariantDarkHighContrast = Color(0xFF1C2829)
val OnSurfaceVariantDarkHighContrast = Color(0xFFDBE8E9)
val SurfaceTintDarkHighContrast = Color(0xFF7FFFA9)
val InverseSurfaceDarkHighContrast = Color(0xFFF5FAFA)
val InverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val ErrorDarkHighContrast = Color(0xFFFFDEDD)
val OnErrorDarkHighContrast = Color(0xFF600013)
val ErrorContainerDarkHighContrast = Color(0xFFFF7B80)
val OnErrorContainerDarkHighContrast = Color(0xFF000000)
val OutlineDarkHighContrast = Color(0xFFAEBBBC)
val OutlineVariantDarkHighContrast = Color(0xFF99A6A7)
val ScrimDarkHighContrast = Color(0xFF000000)
val SurfaceBrightDarkHighContrast = Color(0xFF232E2F)
val SurfaceContainerDarkHighContrast = Color(0xFF121B1C)
val SurfaceContainerHighDarkHighContrast = Color(0xFF182122)
val SurfaceContainerHighestDarkHighContrast = Color(0xFF1C2829)
val SurfaceContainerLowDarkHighContrast = Color(0xFF0D1515)
val SurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val SurfaceDimDarkHighContrast = Color(0xFF0A0F10)

val PrimaryFixedHighContrast = Color(0xFF005F31)
val PrimaryFixedDimHighContrast = Color(0xFF005229)
val OnPrimaryFixedHighContrast = Color(0xFFFFFFFF)
val OnPrimaryFixedVariantHighContrast = Color(0xFFFFFFFF)
val SecondaryFixedHighContrast = Color(0xFF435747)
val SecondaryFixedDimHighContrast = Color(0xFF384B3C)
val OnSecondaryFixedHighContrast = Color(0xFFFFFFFF)
val OnSecondaryFixedVariantHighContrast = Color(0xFFFFFFFF)
val TertiaryFixedHighContrast = Color(0xFF006019)
val TertiaryFixedDimHighContrast = Color(0xFF005314)
val OnTertiaryFixedHighContrast = Color(0xFFFFFFFF)
val OnTertiaryFixedVariantHighContrast = Color(0xFFFFFFFF)